stages:
  train:
    cmd: ipython notebooks/Fixed\ Hyperparameters.ipynb
    deps:
    - cogponder
    - data
    params:
    - params.yaml:
    outs:
    - models
    metrics:
    - metrics.json:
        cache: false
    plots:
    - outputs/plots:
        cache: false
