name: ponder
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - flake8
  - ipywidgets
  - pip:
    - torch
    - torchvision
    - torchaudio
    # - tensorflow
    # - tensorboard
    - torch-tb-profiler
    - scikit-learn
    - tqdm
    - pandas
    - seaborn
