# Note: This file is used to add additional dependencies for a GPU environment.
# Usage: mamba create -f environment.yml -f environment_gpu.yml

name: cogponder

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - pytorch-cuda=11.7
