# Note: This file is used to add additional dependencies for a GPU environment.
# e.g., mamba env create -f environment.yml -f environment_gpu.yml

name: cogponder

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python
  - pip
  - pytest
  - ipykernel
  - jupyter
  - notebook
  - flake8
  - dvc
  - pytorch
  - pytorch-cuda=11.7
  - pytorch-lightning
  - tensorboard
  - torchinfo
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - xarray
  # - ray-tune
