name: ponder
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - flake8
  - ipywidgets>=7.0,<8.0  # to resolve a bug showing tqdm progress bars in VSCode notebook
  - tqdm
  - pytest
  - pip:
    - torch
    - torchvision
    - torchaudio
    - pytorch-lightning
    - ray[tune]
    - rich  # required by a custom lightning progress bar callback
    # - tensorflow
    # - tensorboard
    - torch-tb-profiler
    - scikit-learn
    - pandas
    - seaborn
